prediction_filepath: data/predictions2
benchmark_filepath: data/parsed_benchmark
predictor_group_name: ExamplePredictionsLab1
model_id: 1
ontologies: [CCO, BPO, MFO]


benchmark_json_directory: ./data/parsed_benchmark
dag_ic_directory: ./data_v3/dag_ia
raw_predictions_directory: /media/airport/cafa3_submissions/ExamplePredictionsLab1
predictions_json_directory: ./data_v3/parsed_predictions/ExamplePredictionsLab1/json
predictions_dataframes_directory: ./data_v3/parsed_predictions/ExamplePredictionsLab1/dataframes

# delimiter needs to be quoted:
prediction_file_delimiter: "\t"
prediction_file_header_line_count: 4
knowledge_type: 1
propagation_df_directory: ./data/propagation
#output_directory: ./data2
