predictor_group_name: ExamplePredictionsLab1
model_id: 1
ontologies: [CCO, BPO, MFO]

# Locations for benchmark data:
raw_benchmark_path: /media/airport/cafa3_submissions/test/benchmark/raw
benchmark_json_directory: /media/airport/cafa3_submissions/test/benchmark/parsed_benchmark
dag_ic_directory: /media/airport/cafa3_submissions/test/dag_ia
propagation_df_directory: /media/airport/cafa3_submissions/test/propagation

# Locations for prediction data:
raw_predictions_directory: /media/airport/cafa3_submissions/ExamplePredictionsLab1
predictions_json_directory: /media/airport/cafa3_submissions/test/parsed_predictions/ExamplePredictionsLab1/json
predictions_dataframes_directory: /media/airport/cafa3_submissions/test/parsed_predictions/ExamplePredictionsLab1/dataframes
# delimiter needs to be quoted:
prediction_file_delimiter: "\t"
prediction_file_header_line_count: 4
knowledge_type: 1

